const P='http://schemas.openxmlformats.org/presentationml/2006/main', A='http://schemas.openxmlformats.org/drawingml/2006/main', R='http://schemas.openxmlformats.org/package/2006/relationships';
export const parse=xml=>{const d=new DOMParser().parseFromString(xml,'application/xml');if(d.querySelector('parsererror'))throw Error('模板 XML 损坏');return d;};
const xml=d=>new XMLSerializer().serializeToString(d);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const runXml=(text,size,math=false,superScript=false)=>`<a:r><a:rPr lang="${math?'en-US':'zh-CN'}" sz="${size*100}" b="1"${superScript?' baseline="30000"':''}><a:solidFill><a:srgbClr val="FFFFFF"/></a:solidFill><a:latin typeface="${math?'Cambria Math':'Source Han Sans SC'}"/><a:ea typeface="${math?'Cambria Math':'思源黑体'}"/><a:cs typeface="${math?'Cambria Math':'Source Han Sans SC'}"/></a:rPr><a:t xml:space="preserve">${esc(text)}</a:t></a:r>`;
const questionPrefix=/^(\s*(?:(?:第\s*)?\d+\s*(?:[.．、]|题(?:[.．、])?)|[（(]\s*\d+\s*[）)])\s*)/;
const plainText=/[\u3400-\u9fff\u3000-\u303f，。！？；：“”‘’《》【】（）]+/g;
const normalizeLatex=s=>s.replace(/\s*·\s*/g,' \\cdot ').replace(/\s*×\s*/g,' \\times ').replace(/\s*÷\s*/g,' \\div ').replace(/\s*≤\s*/g,' \\le ').replace(/\s*≥\s*/g,' \\ge ').replace(/\s*≠\s*/g,' \\ne ').replace(/\s*→\s*/g,' \\to ').replace(/²/g,'^{2}').replace(/³/g,'^{3}');
const formulaizePlain=(text,keepQuestionNumber=true)=>{let prefix='',s=text;if(keepQuestionNumber){const m=s.match(questionPrefix);if(m){prefix=m[1];s=s.slice(m[1].length);}}let out=prefix,last=0;for(const m of s.matchAll(plainText)){const segment=s.slice(last,m.index),lead=segment.match(/^\s*/)[0],trail=segment.match(/\s*$/)[0],core=segment.slice(lead.length,segment.length-trail.length);out+=lead+(core?`$${normalizeLatex(core)}$`:'')+trail+m[0];last=m.index+m[0].length;}const segment=s.slice(last),lead=segment.match(/^\s*/)[0],trail=segment.match(/\s*$/)[0],core=segment.slice(lead.length,segment.length-trail.length);return out+lead+(core?`$${normalizeLatex(core)}$`:'')+trail;};
export const autoFormulaizeText=text=>String(text).split('\n').map(line=>{if(/^\s*\$\$[\s\S]*\$\$\s*$/.test(line))return line;let out='',last=0;for(const m of line.matchAll(/\$([^$]+)\$/g)){out+=formulaizePlain(line.slice(last,m.index),last===0)+m[0];last=m.index+m[0].length;}out+=formulaizePlain(line.slice(last),last===0);return out;}).join('\n');
const greek={alpha:'α',beta:'β',gamma:'γ',delta:'δ',theta:'θ',lambda:'λ',mu:'μ',pi:'π',rho:'ρ',sigma:'σ',phi:'φ',omega:'ω',Delta:'Δ',Pi:'Π',Sigma:'Σ',Omega:'Ω'};
export const displayMathText=text=>{let s=String(text).replace(/\$\$/g,'').replace(/\$/g,'').replace(/\\frac\{([^{}]+)\}\{([^{}]+)\}/g,'($1)/($2)').replace(/\\sqrt\{([^{}]+)\}/g,'√($1)').replace(/\\vec\{([^}]+)\}/g,'$1⃗').replace(/\\cdot\s*/g,'·').replace(/\\times\s*/g,'×').replace(/\\div\s*/g,'÷').replace(/\\le\s*/g,'≤').replace(/\\ge\s*/g,'≥').replace(/\\ne\s*/g,'≠').replace(/\\to\s*/g,'→');for(const [name,value] of Object.entries(greek))s=s.replace(new RegExp(`\\\\${name}\\b`,'g'),value);return s.replace(/_\{?([A-Za-z0-9+\-]+)\}?/g,'₍$1₎').replace(/\^\{?2\}?/g,'²').replace(/\^\{?3\}?/g,'³').replace(/\s*-\s*/g,' − ');};
const ommlRun=(text,size)=>`<m:r><m:rPr><m:sty m:val="bi"/></m:rPr><a:rPr lang="en-US" sz="${size*100}" b="1"><a:solidFill><a:srgbClr val="FFFFFF"/></a:solidFill><a:latin typeface="Cambria Math"/><a:ea typeface="Cambria Math"/><a:cs typeface="Cambria Math"/></a:rPr><m:t xml:space="preserve">${esc(text)}</m:t></m:r>`;
const latexBody=(latex,size)=>{let s=latex.trim(),out='';while(s){let m;if((m=s.match(/^\\frac\{([^{}]+)\}\{([^{}]+)\}/))){out+=`<m:f><m:fPr/><m:num>${latexBody(m[1],size)}</m:num><m:den>${latexBody(m[2],size)}</m:den></m:f>`;s=s.slice(m[0].length);}else if((m=s.match(/^\\sqrt\{([^{}]+)\}/))){out+=`<m:rad><m:radPr><m:degHide m:val="1"/></m:radPr><m:deg/><m:e>${latexBody(m[1],size)}</m:e></m:rad>`;s=s.slice(m[0].length);}else if((m=s.match(/^\\vec\{([^}]+)\}/))){out+=`<m:acc><m:accPr><m:chr m:val="⃗"/></m:accPr><m:e>${latexBody(m[1],size)}</m:e></m:acc>`;s=s.slice(m[0].length);}else if((m=s.match(/^\\(cdot|times|div|le|ge|ne|to)\s*/))){out+=ommlRun(({cdot:'·',times:'×',div:'÷',le:'≤',ge:'≥',ne:'≠',to:'→'})[m[1]],size);s=s.slice(m[0].length);}else if((m=s.match(/^\\([A-Za-z]+)\s*/))&&greek[m[1]]){out+=ommlRun(greek[m[1]],size);s=s.slice(m[0].length);}else if((m=s.match(/^([A-Za-z0-9Α-ω]+)(?:_\{([^}]+)\}|_([A-Za-z0-9+\-]+))?(?:\^\{([^}]+)\}|\^([A-Za-z0-9+\-]+))?/))){const base=ommlRun(m[1],size),sub=m[2]||m[3],sup=m[4]||m[5];if(sub&&sup)out+=`<m:sSubSup><m:sSubSupPr/><m:e>${base}</m:e><m:sub>${latexBody(sub,Math.max(8,size-5))}</m:sub><m:sup>${latexBody(sup,Math.max(8,size-5))}</m:sup></m:sSubSup>`;else if(sub)out+=`<m:sSub><m:sSubPr/><m:e>${base}</m:e><m:sub>${latexBody(sub,Math.max(8,size-5))}</m:sub></m:sSub>`;else if(sup)out+=`<m:sSup><m:sSupPr/><m:e>${base}</m:e><m:sup>${latexBody(sup,Math.max(8,size-5))}</m:sup></m:sSup>`;else out+=base;s=s.slice(m[0].length);}else if((m=s.match(/^\s+/))){out+=ommlRun(' ',size);s=s.slice(m[0].length);}else{const ch=s[0]==='-'?'−':s[0];out+=ommlRun(ch,size);s=s.slice(1);}}return out;};
const mathXml=(latex,size,display=false)=>`<a14:m xmlns:a14="http://schemas.microsoft.com/office/drawing/2010/main">${display?`<m:oMathPara xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"><m:oMathParaPr><m:jc m:val="centerGroup"/></m:oMathParaPr><m:oMath>${latexBody(latex,size)}</m:oMath></m:oMathPara>`:`<m:oMath xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math">${latexBody(latex,size)}</m:oMath>`}</a14:m>`;
const paragraphXml=(source,size)=>{const text=autoFormulaizeText(source),display=text.trim().match(/^\$\$([\s\S]+)\$\$$/);let runs;if(display)runs=mathXml(display[1],size,true);else{runs='';let last=0;for(const m of text.matchAll(/\$([^$]+)\$/g)){if(m.index>last)runs+=runXml(text.slice(last,m.index),size);runs+=mathXml(m[1],size);last=m.index+m[0].length;}if(last<text.length)runs+=runXml(text.slice(last),size);}return `<a:p><a:pPr algn="ctr"><a:lnSpc><a:spcPct val="110000"/></a:lnSpc></a:pPr>${runs}<a:endParaRPr sz="${size*100}" b="1"><a:latin typeface="Cambria Math"/><a:ea typeface="思源黑体"/></a:endParaRPr></a:p>`;};
const fragment=s=>parse(`<p:sld xmlns:p="${P}" xmlns:a="${A}" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">${s}</p:sld>`).documentElement.firstChild;
const geometryTextXml=(text,size,color='FFFFFF')=>`<a:p><a:pPr algn="ctr"/><a:r><a:rPr lang="en-US" sz="${size*100}" b="1" i="1"><a:solidFill><a:srgbClr val="${color.replace('#','').toUpperCase()}"/></a:solidFill><a:latin typeface="Cambria Math"/><a:ea typeface="Cambria Math"/></a:rPr><a:t>${esc(text)}</a:t></a:r><a:endParaRPr sz="${size*100}"/></a:p>`;
export async function readTemplate(buffer){
 const zip=await JSZip.loadAsync(buffer);let total=0;for(const f of Object.values(zip.files)){total+=f._data?.uncompressedSize||0;if(total>150*1024*1024)throw Error('模板解压后超过 150 MB，请精简后重试');}
 const pres=zip.file('ppt/presentation.xml'),rels=zip.file('ppt/_rels/presentation.xml.rels');if(!pres||!rels)throw Error('不是有效的 PPTX 模板');
 const doc=parse(await pres.async('string')),rd=parse(await rels.async('string'));
 const size=doc.getElementsByTagNameNS(P,'sldSz')[0];if(!size)throw Error('模板缺少页面尺寸');
 const slides=[...doc.getElementsByTagNameNS(P,'sldId')].map(el=>{const id=el.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id');const rel=[...rd.documentElement.children].find(r=>r.getAttribute('Id')===id);const target=rel?.getAttribute('Target');if(!target||target.includes('..'))throw Error('不支持的模板页路径');return target.startsWith('/')?target.slice(1):'ppt/'+target;});
 if(!slides.length||slides.some(p=>!zip.file(p)))throw Error('模板没有有效幻灯片');
 const thumb=zip.file('docProps/thumbnail.jpeg')||zip.file('docProps/thumbnail.jpg')||zip.file('docProps/thumbnail.png');
 return{buffer,slides,width:+size.getAttribute('cx'),height:+size.getAttribute('cy'),thumbnail:thumb?new Blob([await thumb.async('arraybuffer')],{type:thumb.name.endsWith('.png')?'image/png':'image/jpeg'}):null};
}
export function fitText(text,w,h,maxSize=32){text=displayMathText(text);const ctx=document.createElement('canvas').getContext('2d');for(let size=Math.max(8,Math.min(72,+maxSize||32));size>=8;size--){ctx.font=`bold ${size}px "Source Han Sans SC", "思源黑体", sans-serif`;let lines=0;for(const para of text.split('\n')){let width=0;lines++;for(const ch of para){const cw=ctx.measureText(ch).width;if(width+cw>w-8){lines++;width=0;}width+=cw;}}if(lines*size*1.22<=h-6)return size;}return null;}
export function layoutRegions(template,regions,options={}){
 const textSize=Math.max(8,Math.min(72,+options.textSize||32)),textY=Math.max(0,Math.min(.45,(+options.textY||14)/100)),imageY=Math.max(0,Math.min(1,(+options.imageY||58)/100)),imageScale=Math.max(.2,Math.min(1.4,(+options.imageScale||72)/100));
 const W=template.width,H=template.height,texts=regions.filter(r=>r.type==='text'&&r.text.trim()),images=regions.filter(r=>r.type==='image'&&r.png),placed=[];
 const marginX=W*.08,titleTop=H*textY,titleBottom=titleTop+H*.22,titleGap=H*.012;
 const textH=texts.length?Math.max(H*.055,(titleBottom-titleTop-titleGap*(texts.length-1))/texts.length):0;
 texts.forEach((r,i)=>placed.push({...r,pptX:marginX,pptY:titleTop+i*(textH+titleGap),pptW:W-marginX*2,pptH:textH,align:'center',fontSize:textSize}));
 const imageAreaTop=Math.max(titleBottom+H*.025,H*.05),imageAreaBottom=H*.94,gap=H*.025,count=Math.max(1,images.length),maxItemH=(imageAreaBottom-imageAreaTop-gap*(count-1))/count;
 if(images.length>1){const minX=Math.min(...images.map(r=>r.x||0)),minY=Math.min(...images.map(r=>r.y||0)),maxX=Math.max(...images.map(r=>(r.x||0)+(r.w||1))),maxY=Math.max(...images.map(r=>(r.y||0)+(r.h||1))),sourceW=maxX-minX,sourceH=maxY-minY,distinct=new Set(images.map(r=>`${Math.round(r.x||0)},${Math.round(r.y||0)}`)).size>1;if(distinct&&sourceW>1&&sourceH>1){let scale=Math.min(W*.82/sourceW,H*.58/sourceH)*imageScale,groupW=sourceW*scale,groupH=sourceH*scale;if(groupW>W*.94||groupH>H*.82){const cap=Math.min(W*.94/groupW,H*.82/groupH);scale*=cap;groupW*=cap;groupH*=cap;}const startX=(W-groupW)/2,startY=Math.max(0,H-groupH)*imageY;for(const r of images)placed.push({...r,pptX:startX+((r.x||0)-minX)*scale,pptY:startY+((r.y||0)-minY)*scale,pptW:(r.w||1)*scale,pptH:(r.h||1)*scale});return placed;}const cols=Math.ceil(Math.sqrt(images.length)),rows=Math.ceil(images.length/cols),areaW=W*.86,areaH=H*.62,cellW=areaW/cols,cellH=areaH/rows,groupTop=Math.max(0,H-areaH)*imageY;images.forEach((r,i)=>{const aspect=(r.pngWidth||r.w)/(r.pngHeight||r.h),baseW=Math.min(cellW*.86,cellH*.82*aspect),w=Math.min(cellW*.94,baseW*imageScale),h=w/aspect,col=i%cols,row=Math.floor(i/cols);placed.push({...r,pptX:(W-areaW)/2+col*cellW+(cellW-w)/2,pptY:groupTop+row*cellH+(cellH-h)/2,pptW:w,pptH:h});});return placed;}
 const specs=images.map(r=>{const aspect=(r.pngWidth||r.w)/(r.pngHeight||r.h),baseW=Math.min(W*.65,maxItemH*aspect),baseH=baseW/aspect,w=Math.min(W*.94,baseW*imageScale),h=Math.min(H*.8,baseH*imageScale);return{r,w,h};}),groupH=specs.reduce((sum,s)=>sum+s.h,0)+gap*Math.max(0,specs.length-1);let cursorY=Math.max(0,H-groupH)*imageY;for(const s of specs){placed.push({...s.r,pptX:(W-s.w)/2,pptY:cursorY,pptW:s.w,pptH:s.h});cursorY+=s.h+gap;}
 return placed;
}
export async function makePptx(template,index,regions,imageWidth,imageHeight,options={}){
 const zip=await JSZip.loadAsync(template.buffer),slidePath=template.slides[index],doc=parse(await zip.file(slidePath).async('string')),tree=doc.getElementsByTagNameNS(P,'spTree')[0];if(!tree)throw Error('模板页结构不受支持');
 let id=Math.max(1,...[...doc.getElementsByTagNameNS(P,'cNvPr')].map(e=>+e.getAttribute('id')||0))+1;
 const rp=slidePath.replace(/([^/]+)$/,'_rels/$1.rels');const rd=zip.file(rp)?parse(await zip.file(rp).async('string')):parse(`<Relationships xmlns="${R}"/>`);
 const ct=parse(await zip.file('[Content_Types].xml').async('string'));
 if(![...ct.documentElement.children].some(e=>e.getAttribute('Extension')==='png')){const e=ct.createElementNS(ct.documentElement.namespaceURI,'Default');e.setAttribute('Extension','png');e.setAttribute('ContentType','image/png');ct.documentElement.append(e);}
 for(const region of [...layoutRegions(template,regions,options).filter(r=>r.type==='image'),...layoutRegions(template,regions,options).filter(r=>r.type==='text')]){const x=Math.round(region.pptX),y=Math.round(region.pptY),w=Math.round(region.pptW),h=Math.round(region.pptH),sid=id++;
 const xfrm=`<a:xfrm><a:off x="${x}" y="${y}"/><a:ext cx="${w}" cy="${h}"/></a:xfrm>`;
 if(region.type==='text'){
 if(!region.text.trim())continue;const size=fitText(region.text,w/12700,h/12700,region.fontSize||options.textSize);if(!size)throw Error(`文字即使缩小到 8 pt 仍放不下：${region.text.slice(0,18)}。请缩短文字或拆分段落。`);
 const runs=region.text.split('\n').map(t=>paragraphXml(t,size)).join('');
 tree.appendChild(doc.importNode(fragment(`<p:sp><p:nvSpPr><p:cNvPr id="${sid}" name="Agent 文本 ${sid}"/><p:cNvSpPr txBox="1"/><p:nvPr/></p:nvSpPr><p:spPr>${xfrm}<a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:noFill/><a:ln><a:noFill/></a:ln></p:spPr><p:txBody><a:bodyPr wrap="square" lIns="0" rIns="0" tIns="0" bIns="0"><a:noAutofit/></a:bodyPr><a:lstStyle/>${runs}</p:txBody></p:sp>`),true));
 }else if(region.renderMode==='semantic'&&region.aiProfile?.semantic){
 const s=region.aiProfile.semantic,vertices=new Map(s.vertices.map(v=>[v.id,v])),gx=v=>Math.round(x+w*(.07+v/1000*.86)),gy=v=>Math.round(y+h*(.07+v/1000*.86)),lineWidth=Math.round(Math.max(1,Math.min(4,+options.lineWidth||2))*12700);
 const addLine=(a,b,name,style={})=>{const x1=gx(a.x),y1=gy(a.y),x2=gx(b.x),y2=gy(b.y),lx=Math.min(x1,x2),ly=Math.min(y1,y2),lw=Math.max(1,Math.abs(x2-x1)),lh=Math.max(1,Math.abs(y2-y1)),flipH=x2<x1?' flipH="1"':'',flipV=y2<y1?' flipV="1"':'',stroke=(style.color||'#ffffff').replace('#','').toUpperCase(),strokeWidth=Math.round(Math.max(1,Math.min(12,+style.width||+options.lineWidth||2))*12700);tree.appendChild(doc.importNode(fragment(`<p:sp><p:nvSpPr><p:cNvPr id="${id}" name="${esc(name)} ${id}"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm${flipH}${flipV}><a:off x="${lx}" y="${ly}"/><a:ext cx="${lw}" cy="${lh}"/></a:xfrm><a:prstGeom prst="line"><a:avLst/></a:prstGeom><a:ln w="${strokeWidth}" cap="rnd"><a:solidFill><a:srgbClr val="${stroke}"/></a:solidFill><a:round/></a:ln></p:spPr></p:sp>`),true));id++;};
 for(const e of s.edges||[]){const a=vertices.get(e.from),b=vertices.get(e.to);if(a&&b)addLine(a,b,`Agent 几何线 ${e.from}-${e.to}`,e);}for(const a of s.auxiliaries||[])if(a.keep)addLine({x:a.x1,y:a.y1},{x:a.x2,y:a.y2},`Agent 几何标记 ${a.kind}`,a);
 const addLabel=(textValue,lx,ly,labelSize,name,color)=>{const tw=Math.round(w*.13),th=Math.round(h*.14),tx=gx(lx)-tw/2,ty=gy(ly)-th/2;tree.appendChild(doc.importNode(fragment(`<p:sp><p:nvSpPr><p:cNvPr id="${id}" name="${esc(name)} ${id}"/><p:cNvSpPr txBox="1"/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="${Math.round(tx)}" y="${Math.round(ty)}"/><a:ext cx="${tw}" cy="${th}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:noFill/><a:ln><a:noFill/></a:ln></p:spPr><p:txBody><a:bodyPr anchor="ctr" lIns="0" rIns="0" tIns="0" bIns="0"/><a:lstStyle/>${geometryTextXml(textValue,labelSize,color)}</p:txBody></p:sp>`),true));id++;};
 const fontPt=Math.max(18,Math.min(54,Math.round(h/12700*.09)));for(const v of s.vertices)addLabel(v.label,v.label_x,v.label_y,Math.max(16,Math.min(72,v.size||fontPt)),`Agent 几何字母 ${v.label}`,v.color);for(const a of s.annotations||[])addLabel(a.text,a.x,a.y,Math.max(16,Math.min(72,a.size||36)),`Agent 几何标注 ${a.text}`,a.color);
 if(region.watermarkBlob){let name=`agent-watermark-${sid}.png`;while(zip.file('ppt/media/'+name))name='x-'+name;zip.file('ppt/media/'+name,await region.watermarkBlob.arrayBuffer());let rid=`rIdAgentWatermark${sid}`;while([...rd.documentElement.children].some(e=>e.getAttribute('Id')===rid))rid+='x';const rel=rd.createElementNS(R,'Relationship');rel.setAttribute('Id',rid);rel.setAttribute('Type','http://schemas.openxmlformats.org/officeDocument/2006/relationships/image');rel.setAttribute('Target','../media/'+name);rd.documentElement.append(rel);const ww=w*.6,wh=ww*(269/1747);tree.appendChild(doc.importNode(fragment(`<p:pic><p:nvPicPr><p:cNvPr id="${id++}" name="Agent 独立水印 ${sid}"/><p:cNvPicPr><a:picLocks noChangeAspect="1"/></p:cNvPicPr><p:nvPr/></p:nvPicPr><p:blipFill><a:blip r:embed="${rid}"/><a:stretch><a:fillRect/></a:stretch></p:blipFill><p:spPr><a:xfrm><a:off x="${Math.round(x+(w-ww)/2)}" y="${Math.round(y+(h-wh)/2)}"/><a:ext cx="${Math.round(ww)}" cy="${Math.round(wh)}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr></p:pic>`),true));}
 }else{
 if(!region.png)throw Error('有图片尚未生成透明白线图，请点击该图片的生成按钮');
 let name=`agent-${sid}.png`;while(zip.file('ppt/media/'+name))name='x-'+name;
 zip.file('ppt/media/'+name,await region.png.arrayBuffer());let rid=`rIdAgent${sid}`;while([...rd.documentElement.children].some(e=>e.getAttribute('Id')===rid))rid+='x';
 const rel=rd.createElementNS(R,'Relationship');rel.setAttribute('Id',rid);rel.setAttribute('Type','http://schemas.openxmlformats.org/officeDocument/2006/relationships/image');rel.setAttribute('Target','../media/'+name);rd.documentElement.append(rel);
 tree.appendChild(doc.importNode(fragment(`<p:pic><p:nvPicPr><p:cNvPr id="${sid}" name="Agent 透明白线图 ${sid}"/><p:cNvPicPr><a:picLocks noChangeAspect="1"/></p:cNvPicPr><p:nvPr/></p:nvPicPr><p:blipFill><a:blip r:embed="${rid}"/><a:stretch><a:fillRect/></a:stretch></p:blipFill><p:spPr>${xfrm}<a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr></p:pic>`),true));
 }}
 zip.file(slidePath,xml(doc));zip.file(rp,xml(rd));zip.file('[Content_Types].xml',xml(ct));return zip.generateAsync({type:'blob',compression:'DEFLATE',mimeType:'application/vnd.openxmlformats-officedocument.presentationml.presentation'});
}
